name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: 'ubuntu:latest'
            suffix: ''
          - name: 'ubuntu:22.04'
            suffix: '-ubuntu22.04'
          - name: 'ubuntu:20.04'
            suffix: '-ubuntu20.04'
          - name: 'ubuntu:18.04'
            suffix: '-ubuntu18.04'
          - name: 'alpine'
            suffix: '-alpine'
          - name: 'scratch'
            suffix: '-scratch'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./build/package/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.ref_name }}
            APP_IMAGE=${{ matrix.image.name }}
          tags: ghcr.io/dmitryromanov/${{ github.event.repository.name }}:build${{ github.run_number}}${{ matrix.image.suffix }}
